### ISSUE TITLE
False positive kicking almost everyone

### ISSUE THREAD

**Issue by Agaloth** [Nort721/GodsEye-Issues#102]
A bug report/issue report should contain:

1) GodsEye version: build beta 24

2) Server Version+Fork: git-paper-239 (1.14.4)

3) ProtocolLib version: 4.5.0 snapshot

4) Server log: I attached godseye + server logs when I had the anticheat 2 days ago.
https://github.com/Nort721/GodsEye-Issues/files/4080235/godseyelogs.zip <- Godseye logs
https://github.com/Nort721/GodsEye-Issues/files/4080144/2020-01-18-2.log <- Server log

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. I do not have any video or screenshot of the issue.

6) A very detailed description of the issue
The plugin just kicks everyone that plays, it mainly detects movement (TypeF), killaura (TypeC), autoclicker (TypeC, TypeD), inventoryactions (TypeD), speed (TypeB), timer (TypeA), reach (TypeA), some can't move anymore, the server has the Crazy Enchantment and MCMMO plugin, I think that might modify player movement and kick them for no reason, I also verified some players manually and they didn't have any cheats.

**Comment by Nort721** [comment]
Well some of the checks you that you have mentioned are known to be problematic and should of been disabled by default but since we found an issue with the new config that has been released the last update these checks have not been disabled like the should of been, the config issue is already fixed for next update.

For MCMMO and Crazy Enchantments, as said on GodsEye's spigot page plugins that affect gameplay mechanics directly would probably cause issues with the AntiCheat,

For now, all I can do is to make sure to fix the config, I would recommend you to try just disable every check that falses for you because of this plugins, the config will be fixed in Build 25 BETA
I will also take a look at these checks will make sure to fixed or disable the problematic ones for next update
