### ISSUE TITLE
Godseye bot doesn't work

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#113]
Omg im legit done reporting this the godseye bot check still doesn't work for paper 1.12.2

**Comment by Nort721** [comment]
What do you mean by doesn't work? any console errors?

**Comment by Nort721** [comment]
Most likely removing this feature next update or in the one after it

reason:
fixing it would need a rewrite which would take a lot lot of time since it would also need to support like 8 versions which would also take a very big amount of time and all of this work will be for a check that can easily be bypassed by any modern client (and the bypass most of the time can't be fixed which is why most AntiCheats are not using it to detect auras)
