### ISSUE TITLE
Bypassing Autoclicker 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#208]
A bug report/issue report should contain:

1)Test server
2) Test server
3) Test server
4) Test server
5) https://youtu.be/P0BF0vLH71I
6) So I am using this autoclicker called Glock Clicker it is bypassing every server atm, I just wanted to report it since it is also bypassing godseye and it is not an expensive autoclicker...

**Comment by Nort721** [comment]
Most AntiCheats wont detect all kinds of AutoClicker, actually most of them wont detect them at all unlike GodsEye which detects some premium clients and free ones, its one of the hardest hacks to detect which is why we say on the blocked hacks list that we detect TYPES OF AUTOCLICKERS, which means not all of them

Sorry but you can't really expect from us to detect all AutoClicker like you would expect with Speed or Fly.
No need to report AutoClicker bypasses to the issue tracker, we are keeping on improving the check all the time as can be seen in the update logs
