### ISSUE TITLE
Vape V4 Legit Scaffold Bypass

### ISSUE THREAD

**Issue by Kurumi78** [Nort721/GodsEye-Issues#211]
This was all tested on the test server, I do not have the requested info because of this.
5) https://youtu.be/jPavMAzMFoc
6) Pretty simple, Vape V4's legit scaffold bypasses godseye no matter what speed it is set to.

**Comment by Nort721** [comment]
That bypasses every AntiCheat in existence, you literally can't any AntiCheat that detects that cleanly, I will try to patch it though

**Comment by lenis0012** [comment]
This is also known as Eagle.
It is a method of bridging that is possible to achieve in vanilla gameplay by timing your sneak.
Really hard/impossible to detect without falses.

**Comment by Nort721** [comment]
After testing a bit with friends of mine that know some methods of briding I found that this scaffold hack is not faster and sometimes ever slower then normal speed bridging which means that hack is not really giving the player a significant advantage over other players if any

In additing I found that detecting this hack would not be possible without having a risk of false flagging legit players that are just good at bridging

So because this hack is not really giving much of an advantage over other players and it would be very hard and risky to detect I have decided that we are not going to patch it
