### ISSUE TITLE
Ignore op players

### ISSUE THREAD

**Issue by Green-Sickness** [Nort721/GodsEye-Issues#218]
A bug report/issue report should contain:

Server Version+Fork: N/A
ProtocolLib version: N/A
Server log: N/A
We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: N/A
A very detailed description of the issue: possibly add ignore Op players , would allow to dectect op Players but not those with godseye.bypass

**Comment by Nort721** [comment]
OP players are currently ignored because by being op they automatically have the GodsEye.bypass permission, I guess I can make some option to make it check op players also though

**Comment by Green-Sickness** [comment]
That would be great :+1:

**Comment by Nort721** [comment]
I checked it and OP players are currently not checked by GodsEye because when you are OP you automatically have all of the permissions on the server, I have decided to make changes to the idea and implement the /ge checkall commands which basically makes GodsEye check all of the players in the server and it ignores the GodsEye.bypass permission

you can use the same command again to make it not ignore the permission like before, I hope that you will find this useful to solve the problem

**Comment by Green-Sickness** [comment]
Is it possible to add a setting in config to toggle it om forever

**Comment by Nort721** [comment]
you can use the command to toggle it
