### ISSUE TITLE
[Feature Request] More Config Customization

### ISSUE THREAD

**Issue by Officiated** [Nort721/GodsEye-Issues#225]
A bug report/issue report should contain:

1) GodsEye version
N/A
2) Server Version+Fork
N/A
3) ProtocolLib version
N/A
4) Server log
N/A
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A
6) A very detailed description of the issue
Add a violation divisor in checks.yml which by default is 1 because VLs increase by 1 each time but would allow you to change it to a higher number to help prevent your chat from being spammed. For example, if you set the violation divisor for the Fly check to 5 then the verbose message won't show until the player has reached a VL of 5 then 10, 15, etc. 
Something else that might be useful is adding the "Max violations:" to each type (TypeA, TypeB, etc.) because I've found that some types are more accurate/less likely to false flag and therefore may want a lower VL before a kick/ban for that particular type.

**Comment by Nort721** [comment]
The violations devisor is not needed since thats why we have the alerts system for, just disable verbose and use alerts, you can set alerts to be sent in every amount of violations you want, verbose alerts are only meant for testing and debugging, you can also configure alerts to show all the information you want

For the max violations per type, I will think about it eventionally we plan to reach a state where all the types are stable enough but I can see where the idea is coming from so I will consider it

**Comment by Nort721** [comment]
I close this request for now, although I may will reopen it in the future
