### ISSUE TITLE
1.14.4 Paper Support

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#24]
1) Paper 1.14.4
2) 4.5.0-SNAPSHOT
3) not required as there is no console error or anything the plugin loads and works fine
4) N/A
5) i've already reported this to nort on discord he asked me to do so on here on 1.14.4 paper no check is being detected  i used flux tried every blatant hacks including fly and speed none of them work

Nort's reply:
just tested on paper 1.14.4 with flux b13, 0 console errors all detected
if you have banning disabled try setting the kicks number to like 100000
maybe related
hmm ok I found an error
will test if it happends also on normal 1.14.4
ok I found the problem
looks like there is a bug with kicking \
will release a hotfix for that when I will be able to
anyways create a quick issue on the tracker for that so I will remember to work on this once I'll have time

**AND PLEASE WHY DID YOU CLOSE MY GODSEYE 1.14.4 CONSOLE COMMAND PROBLEM? WHENEVER I DO /godseye on console nothing happens i just get a error: https://hastebin.com/xukupenige.bash**

**Comment by Nort721** [comment]
well nothing on Flux is bypassing GodsEye as said, in your case, there is an error that prevents GodsEye from checking the player in the first place, this issue only happens on 1.14.4 servers sometimes and it is one of the reasons we are recoding the plugin.
also I have closed the issue because I solved it, I have just didn't released the update with the fix because we have decided to recode the plugin, also you should not use this command in the console anyways

**Comment by Nort721** [comment]
Should be fixed once the recode is out, paper is still not officially supported but still should work just fine, if not we are still willing to fix issues with paper
