### ISSUE TITLE
request

### ISSUE THREAD

**Issue by slumbery** [Nort721/GodsEye-Issues#4]
maybe add a /report command instead of using a report plugin

**Comment by Adriuoda** [comment]
There is too many report plugins in spigotmc, u can download one.
this is anticheat not report + report can't be a feature for a Anticheat.

**Comment by Nort721** [comment]
well I can understand the convenience of having all cheater/trollers information stored in once place can be a comfortable thing but since GodsEye is AntiCheat we prefer focusing on Cheat Detection and stability while providing updates as fast as we can so, unfortunately, there is currently no place for none AntiCheat related systems to be added and will likely won't be a place for them in the future
