### ISSUE TITLE
Empty Packets / BungeeCord compatibility

### ISSUE THREAD

**Issue by Nqtsu91** [Nort721/GodsEye-Issues#490]
1) Build 62
2) Paper 1.8.8-445 [BungeeCord NetWork]
3) Lunar Client <any version>
4) ProtocolLib -latest
5) No console errors
7) Sometime, randomly, on a BungeeCord network, players get kicked out of the current server, with the message "Server went down, connecting to a fallback server". According to md-5, this come from a plugin sending an empty packet to a player, often caused by AntiCheat and AntiExploits.
In my case, it seem to be coming from GodsEye, since its the only plugin using packets.

I cant really troubleshoot whats causing the issue exactly, since it happen randomly

**Comment by 0xntpower** [comment]
I have implemented a fix in Build 63 (which has just been released as I'm writing this) but since this issue is hard to replicate I'll appreciate it if you'll let me know if you encounter this problem again after upgrading to build 63
if you will I will reopen the issue and will try solving it from another direction, however for now I'll consider it as fixed
