### ISSUE TITLE
question

### ISSUE THREAD

**Issue by coolpvpv1** [Nort721/GodsEye-Issues#60]
i try to join the test server to test hacks and im ip banned? my ign is Hatz_N_TonezK97 why am i banned? only thing ive done is just test the anticheat

**Comment by Nort721** [comment]
You can ask questions on discors if you want, the only thing that is a must to do in tbe issue tracker is reporting issues and requesting features

For the ban I am not sure since TopRaider is the one responsible for banning from the test server, normally players get banned from them for developing bypasses for thier clients or for being toxic, I will be checking with him about your ban

**Comment by Nort721** [comment]
Did you remember an incident of you being toxic towards other players in the server or towards GodsEye?

**Comment by Nort721** [comment]
Ok I have your ban reason, DM on discord if you want to see it
