### ISSUE TITLE
PingSpoof (Type A and B)

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#81]
A bug report/issue report should contain:

1) Server Version+Fork: The official testing server's.
2) ProtocolLib version: The official testing server's.
3) Server log: I don't have it cuz it's a official testing server.
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/p18j8
5) A very detailed description of the issue: Keep standing.

**Comment by Nort721** [comment]
TypeB is a work in progress, TypeA may throw random flags if you have high ping but again not enough to cause a punishment,

If the video TypeB was responsible for your kick since it was built to add a lot of flags at once, but as said its a work in progress

I will be taking a look at them thanks for reporting
